"""add smart fit

Smart Fit: confirmed Fit Profiles and recent photo estimates (derived
numbers only, never images).

Revision ID: 4d866ba77cda
Revises: 1bb8ac730c3f
Create Date: 2026-10-03 15:05:30.257018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d866ba77cda'
down_revision: Union[str, Sequence[str], None] = '1bb8ac730c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fit_estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=False),
    sa.Column('fit_preference', sa.Enum('slim', 'regular', 'relaxed', name='fit_preference', native_enum=False, create_constraint=True, length=10), nullable=False),
    sa.Column('used_side_photo', sa.Boolean(), nullable=False),
    sa.Column('shoulder_width_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('chest_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('waist_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('hip_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('inseam_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('suggested_top_size', sa.String(length=10), nullable=True),
    sa.Column('suggested_bottom_size', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('estimation_version', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_fit_estimates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fit_estimates'))
    )
    op.create_index(op.f('ix_fit_estimates_user_id'), 'fit_estimates', ['user_id'], unique=False)
    op.create_table('fit_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=False),
    sa.Column('fit_preference', sa.Enum('slim', 'regular', 'relaxed', name='fit_preference', native_enum=False, create_constraint=True, length=10), nullable=False),
    sa.Column('top_size', sa.String(length=10), nullable=True),
    sa.Column('bottom_size', sa.String(length=10), nullable=True),
    sa.Column('shoe_size_eu', sa.Integer(), nullable=True),
    sa.Column('estimated_shoulder_width_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('estimated_chest_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('estimated_waist_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('estimated_hip_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('estimated_inseam_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('estimation_version', sa.String(length=80), nullable=True),
    sa.Column('confirmed_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_fit_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fit_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_fit_profiles_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fit_profiles')
    op.drop_index(op.f('ix_fit_estimates_user_id'), table_name='fit_estimates')
    op.drop_table('fit_estimates')
    # ### end Alembic commands ###
