"""add visual search index

Image embeddings per product image and model (float32 bytes), and a log of
index runs for the admin status page. No changes to existing tables.

Revision ID: 1bb8ac730c3f
Revises: 52a6cf50e536
Create Date: 2026-10-03 12:59:31.707066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bb8ac730c3f'
down_revision: Union[str, Sequence[str], None] = '52a6cf50e536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visual_search_index_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('indexed', sa.Integer(), nullable=False),
    sa.Column('unchanged', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visual_search_index_runs'))
    )
    op.create_table('product_image_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_image_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('source_path', sa.String(length=255), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_image_id'], ['product_images.id'], name=op.f('fk_product_image_embeddings_product_image_id_product_images'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_image_embeddings')),
    sa.UniqueConstraint('product_image_id', 'model_name', name='uq_product_image_embeddings_image_model')
    )
    op.create_index(op.f('ix_product_image_embeddings_product_image_id'), 'product_image_embeddings', ['product_image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_image_embeddings_product_image_id'), table_name='product_image_embeddings')
    op.drop_table('product_image_embeddings')
    op.drop_table('visual_search_index_runs')
    # ### end Alembic commands ###
