"""add returns and support

Returns (requests, items, status history) and customer support conversations
with plain-text messages. No uploaded files are stored.

Revision ID: 56c84faf7a63
Revises: 4d866ba77cda
Create Date: 2026-10-03 16:57:15.816313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c84faf7a63'
down_revision: Union[str, Sequence[str], None] = '4d866ba77cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('return_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_number', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('requested', 'approved', 'rejected', 'received', 'refunded', 'cancelled', name='return_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('reason_summary', sa.String(length=120), nullable=False),
    sa.Column('customer_note', sa.String(length=1000), nullable=True),
    sa.Column('return_value', sa.Integer(), nullable=False),
    sa.Column('refunded_amount', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('refunded_amount IS NULL OR refunded_amount >= 0', name=op.f('ck_return_requests_refunded_amount_non_negative')),
    sa.CheckConstraint('return_value >= 0', name=op.f('ck_return_requests_return_value_non_negative')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_return_requests_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_return_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_return_requests'))
    )
    op.create_index(op.f('ix_return_requests_order_id'), 'return_requests', ['order_id'], unique=False)
    op.create_index(op.f('ix_return_requests_return_number'), 'return_requests', ['return_number'], unique=True)
    op.create_index(op.f('ix_return_requests_status'), 'return_requests', ['status'], unique=False)
    op.create_index(op.f('ix_return_requests_user_id'), 'return_requests', ['user_id'], unique=False)
    op.create_table('return_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_request_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('requested', 'approved', 'rejected', 'received', 'refunded', 'cancelled', name='return_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('customer_note', sa.String(length=500), nullable=True),
    sa.Column('internal_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_return_status_history_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['return_request_id'], ['return_requests.id'], name=op.f('fk_return_status_history_return_request_id_return_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_return_status_history'))
    )
    op.create_index(op.f('ix_return_status_history_return_request_id'), 'return_status_history', ['return_request_id'], unique=False)
    op.create_table('support_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_number', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('return_request_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.Enum('sizing', 'delivery', 'order_issue', 'return_question', 'other', name='support_subject', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='conversation_status', native_enum=False, create_constraint=True, length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_support_conversations_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['return_request_id'], ['return_requests.id'], name=op.f('fk_support_conversations_return_request_id_return_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_support_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_conversations'))
    )
    op.create_index(op.f('ix_support_conversations_conversation_number'), 'support_conversations', ['conversation_number'], unique=True)
    op.create_index(op.f('ix_support_conversations_last_message_at'), 'support_conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_support_conversations_order_id'), 'support_conversations', ['order_id'], unique=False)
    op.create_index(op.f('ix_support_conversations_return_request_id'), 'support_conversations', ['return_request_id'], unique=False)
    op.create_index(op.f('ix_support_conversations_status'), 'support_conversations', ['status'], unique=False)
    op.create_index(op.f('ix_support_conversations_user_id'), 'support_conversations', ['user_id'], unique=False)
    op.create_table('return_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_request_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('wrong_size', 'damaged', 'wrong_item', 'not_as_expected', 'changed_mind', 'other', name='return_reason', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('condition_note', sa.String(length=500), nullable=True),
    sa.Column('restock', sa.Boolean(), nullable=True),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_return_items_quantity_positive')),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_return_items_order_item_id_order_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['return_request_id'], ['return_requests.id'], name=op.f('fk_return_items_return_request_id_return_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_return_items')),
    sa.UniqueConstraint('return_request_id', 'order_item_id', name='uq_return_items_request_order_item')
    )
    op.create_index(op.f('ix_return_items_order_item_id'), 'return_items', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_return_items_return_request_id'), 'return_items', ['return_request_id'], unique=False)
    op.create_table('support_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=True),
    sa.Column('sender_role', sa.Enum('customer', 'store', name='sender_role', native_enum=False, create_constraint=True, length=10), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['support_conversations.id'], name=op.f('fk_support_messages_conversation_id_support_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], name=op.f('fk_support_messages_sender_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_messages'))
    )
    op.create_index('ix_support_messages_conversation_id_id', 'support_messages', ['conversation_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_support_messages_conversation_id_id', table_name='support_messages')
    op.drop_table('support_messages')
    op.drop_index(op.f('ix_return_items_return_request_id'), table_name='return_items')
    op.drop_index(op.f('ix_return_items_order_item_id'), table_name='return_items')
    op.drop_table('return_items')
    op.drop_index(op.f('ix_support_conversations_user_id'), table_name='support_conversations')
    op.drop_index(op.f('ix_support_conversations_status'), table_name='support_conversations')
    op.drop_index(op.f('ix_support_conversations_return_request_id'), table_name='support_conversations')
    op.drop_index(op.f('ix_support_conversations_order_id'), table_name='support_conversations')
    op.drop_index(op.f('ix_support_conversations_last_message_at'), table_name='support_conversations')
    op.drop_index(op.f('ix_support_conversations_conversation_number'), table_name='support_conversations')
    op.drop_table('support_conversations')
    op.drop_index(op.f('ix_return_status_history_return_request_id'), table_name='return_status_history')
    op.drop_table('return_status_history')
    op.drop_index(op.f('ix_return_requests_user_id'), table_name='return_requests')
    op.drop_index(op.f('ix_return_requests_status'), table_name='return_requests')
    op.drop_index(op.f('ix_return_requests_return_number'), table_name='return_requests')
    op.drop_index(op.f('ix_return_requests_order_id'), table_name='return_requests')
    op.drop_table('return_requests')
    # ### end Alembic commands ###
