"""add admin order history fields

Staff-only notes and the acting admin on order status events, and a log of
manual (demo) payment-status changes.

Revision ID: 52a6cf50e536
Revises: 696e4899dad5
Create Date: 2026-10-03 06:25:16.615941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a6cf50e536'
down_revision: Union[str, Sequence[str], None] = '696e4899dad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('pending', 'paid', 'failed', 'refunded', name='from_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('to_status', sa.Enum('pending', 'paid', 'failed', 'refunded', name='to_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], name=op.f('fk_payment_status_history_changed_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payment_status_history_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_status_history'))
    )
    op.create_index(op.f('ix_payment_status_history_order_id'), 'payment_status_history', ['order_id'], unique=False)
    op.add_column('order_status_history', sa.Column('internal_note', sa.String(length=500), nullable=True))
    op.add_column('order_status_history', sa.Column('changed_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_order_status_history_changed_by_user_id_users'), 'order_status_history', 'users', ['changed_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_order_status_history_changed_by_user_id_users'), 'order_status_history', type_='foreignkey')
    op.drop_column('order_status_history', 'changed_by_user_id')
    op.drop_column('order_status_history', 'internal_note')
    op.drop_index(op.f('ix_payment_status_history_order_id'), table_name='payment_status_history')
    op.drop_table('payment_status_history')
    # ### end Alembic commands ###
